// <auto-generated />
using System;
using AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessData.Migrations
{
    [DbContext(typeof(AmhWebDbContext))]
    [Migration("20231206001141_20231205_IngresosPeriodo")]
    partial class _20231205_IngresosPeriodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.Acto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Acto");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.Caratula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Caratula");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.Expediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Avisado")
                        .HasColumnType("bit");

                    b.Property<string>("Documento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("EnviadoLaborales")
                        .HasColumnType("bit");

                    b.Property<string>("Expediente1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Expediente");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaExpediente")
                        .HasColumnType("date");

                    b.Property<bool?>("FirmadoLaborales")
                        .HasColumnType("bit");

                    b.Property<bool?>("FirmadoSumario")
                        .HasColumnType("bit");

                    b.Property<int?>("IdActo")
                        .HasColumnType("int");

                    b.Property<int?>("IdCaratula")
                        .HasColumnType("int");

                    b.Property<int?>("IdSituacionRevista")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdActo");

                    b.HasIndex("IdCaratula");

                    b.HasIndex("IdSituacionRevista");

                    b.ToTable("Expediente");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.SituacionRevista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SituacionRevista");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Banco");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaGasto");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdTarjeta")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdTarjeta");

                    b.HasIndex("IdTipoCuenta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingreso");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("date");

                    b.Property<int?>("IdCategoriaGasto")
                        .HasColumnType("int");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegistroVinculado")
                        .HasColumnType("int");

                    b.Property<int?>("IdSuscripcion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Pagado")
                        .HasColumnType("bit");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(25, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRegistroVinculado");

                    b.HasIndex("IdSuscripcion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Registro");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.RegistroVinculado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cuotas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("numeric(25, 2)");

                    b.HasKey("Id");

                    b.ToTable("RegistroVinculado");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Suscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<int?>("IdCategoriaGasto")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ValorActual")
                        .HasColumnType("numeric(25, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Suscripcion");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdBanco")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoTarjeta")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Vencimiento")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("IdBanco");

                    b.HasIndex("IdTipoTarjeta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.TipoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoCuenta");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.TipoTarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoTarjeta");
                });

            modelBuilder.Entity("Domain.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Domain.Models.MayiBeerCollection.Cerveza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Alcohol")
                        .HasColumnType("float");

                    b.Property<int>("Contenido")
                        .HasColumnType("int");

                    b.Property<double?>("IBU")
                        .HasColumnType("float");

                    b.Property<int?>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstilo")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdEstilo");

                    b.HasIndex("IdMarca");

                    b.ToTable("Cerveza");
                });

            modelBuilder.Entity("Domain.Models.MayiBeerCollection.Estilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Estilo");
                });

            modelBuilder.Entity("Domain.Models.MayiBeerCollection.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Domain.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Domain.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Domain.Models.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sistema");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Domain.Models.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSistema");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioSistema");
                });

            modelBuilder.Entity("Domain.Models.Ciudad", b =>
                {
                    b.HasOne("Domain.Models.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Ciudad_Pais");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.Expediente", b =>
                {
                    b.HasOne("Domain.Models.GestorExpedientes.Acto", "Acto")
                        .WithMany("Expedientes")
                        .HasForeignKey("IdActo")
                        .HasConstraintName("FK_Expediente_Acto");

                    b.HasOne("Domain.Models.GestorExpedientes.Caratula", "Caratula")
                        .WithMany("Expedientes")
                        .HasForeignKey("IdCaratula")
                        .HasConstraintName("FK_Expediente_Caratula");

                    b.HasOne("Domain.Models.GestorExpedientes.SituacionRevista", "SituacionRevista")
                        .WithMany("Expedientes")
                        .HasForeignKey("IdSituacionRevista")
                        .HasConstraintName("FK_Expediente_SituacionRevista");

                    b.Navigation("Acto");

                    b.Navigation("Caratula");

                    b.Navigation("SituacionRevista");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Cuenta", b =>
                {
                    b.HasOne("Domain.Models.GestorGastos.Tarjeta", "Tarjeta")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdTarjeta")
                        .HasConstraintName("FK_Cuenta_Tarjeta");

                    b.HasOne("Domain.Models.GestorGastos.TipoCuenta", "TipoCuenta")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdTipoCuenta")
                        .IsRequired()
                        .HasConstraintName("FK_Cuenta_TipoCuenta");

                    b.HasOne("Domain.Models.Usuario", "Usuario")
                        .WithMany("Cuentas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Cuenta_Usuario");

                    b.Navigation("Tarjeta");

                    b.Navigation("TipoCuenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Ingreso", b =>
                {
                    b.HasOne("Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Registro", b =>
                {
                    b.HasOne("Domain.Models.GestorGastos.CategoriaGasto", "CategoriaGasto")
                        .WithMany("Registros")
                        .HasForeignKey("CategoriaGastoId");

                    b.HasOne("Domain.Models.GestorGastos.Cuenta", "Cuenta")
                        .WithMany("Registros")
                        .HasForeignKey("IdCuenta")
                        .IsRequired()
                        .HasConstraintName("FK_Registro_Cuenta");

                    b.HasOne("Domain.Models.GestorGastos.Empresa", "Empresa")
                        .WithMany("Registros")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK_Registro_Empresa");

                    b.HasOne("Domain.Models.GestorGastos.RegistroVinculado", "RegistroVinculado")
                        .WithMany("Registros")
                        .HasForeignKey("IdRegistroVinculado")
                        .HasConstraintName("FK_Registro_RegistroVinculado");

                    b.HasOne("Domain.Models.GestorGastos.Suscripcion", "Suscripcion")
                        .WithMany("Registros")
                        .HasForeignKey("IdSuscripcion")
                        .HasConstraintName("FK_Registro_Suscripcion");

                    b.HasOne("Domain.Models.Usuario", "Usuario")
                        .WithMany("Registros")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Registro_Usuario");

                    b.Navigation("CategoriaGasto");

                    b.Navigation("Cuenta");

                    b.Navigation("Empresa");

                    b.Navigation("RegistroVinculado");

                    b.Navigation("Suscripcion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Suscripcion", b =>
                {
                    b.HasOne("Domain.Models.GestorGastos.CategoriaGasto", "CategoriaGasto")
                        .WithMany("Suscripciones")
                        .HasForeignKey("CategoriaGastoId");

                    b.HasOne("Domain.Models.Usuario", "Usuario")
                        .WithMany("Suscripciones")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Suscripcion_Usuario");

                    b.Navigation("CategoriaGasto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Tarjeta", b =>
                {
                    b.HasOne("Domain.Models.GestorGastos.Banco", "Banco")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdBanco")
                        .HasConstraintName("FK_Tarjeta_Banco");

                    b.HasOne("Domain.Models.GestorGastos.TipoTarjeta", "TipoTarjeta")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdTipoTarjeta")
                        .HasConstraintName("FK_Tarjeta_TipoTarjeta");

                    b.HasOne("Domain.Models.Usuario", "Usuario")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Tarjeta_Usuario");

                    b.Navigation("Banco");

                    b.Navigation("TipoTarjeta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.MayiBeerCollection.Cerveza", b =>
                {
                    b.HasOne("Domain.Models.Ciudad", "Ciudad")
                        .WithMany("Cervezas")
                        .HasForeignKey("IdCiudad")
                        .HasConstraintName("FK_Cerveza_Ciudad");

                    b.HasOne("Domain.Models.MayiBeerCollection.Estilo", "Estilo")
                        .WithMany("Cervezas")
                        .HasForeignKey("IdEstilo")
                        .HasConstraintName("FK_Cerveza_Estilo");

                    b.HasOne("Domain.Models.MayiBeerCollection.Marca", "Marca")
                        .WithMany("Cervezas")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK_Cerveza_Marca");

                    b.Navigation("Ciudad");

                    b.Navigation("Estilo");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.HasOne("Domain.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .HasConstraintName("FK_Usuario_Perfil");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Domain.Models.UsuarioSistema", b =>
                {
                    b.HasOne("Domain.Models.Sistema", "Sistema")
                        .WithMany("UsuariosSistema")
                        .HasForeignKey("IdSistema")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioSistema_Sistema");

                    b.HasOne("Domain.Models.Usuario", "Usuario")
                        .WithMany("UsuariosSistema")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioSistema_Usuario");

                    b.Navigation("Sistema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Models.Ciudad", b =>
                {
                    b.Navigation("Cervezas");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.Acto", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.Caratula", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("Domain.Models.GestorExpedientes.SituacionRevista", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Banco", b =>
                {
                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.CategoriaGasto", b =>
                {
                    b.Navigation("Registros");

                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Cuenta", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Empresa", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.RegistroVinculado", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Suscripcion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.Tarjeta", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.TipoCuenta", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("Domain.Models.GestorGastos.TipoTarjeta", b =>
                {
                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("Domain.Models.MayiBeerCollection.Estilo", b =>
                {
                    b.Navigation("Cervezas");
                });

            modelBuilder.Entity("Domain.Models.MayiBeerCollection.Marca", b =>
                {
                    b.Navigation("Cervezas");
                });

            modelBuilder.Entity("Domain.Models.Pais", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Domain.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Domain.Models.Sistema", b =>
                {
                    b.Navigation("UsuariosSistema");
                });

            modelBuilder.Entity("Domain.Models.Usuario", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("Registros");

                    b.Navigation("Suscripciones");

                    b.Navigation("Tarjetas");

                    b.Navigation("UsuariosSistema");
                });
#pragma warning restore 612, 618
        }
    }
}
